75 create breadcrumb component
Brisanet/ion-react pull request #115
Opened 2023-03-28 20:36 UTC by Atzac

Breadcrumb feat #75

2023-04-04 20:34 UTC, iurynogueira commented
fix #75

2023-04-10 16:33 UTC, wermesonsl requested changes

2023-04-11 17:37 UTC, Atzac commented on src/components/breadcrumb/breadcrumb.test.tsx
> +  it('should not call the selectedBreadcrumb function when the last breadcrumb is clicked', () => {
O teste anterior se refere ao click no ultimo breadcrumb, Este teste é referente à função "selectedBreadcrumb" que nao deve ser executada com click no ultimo breadcrumb. Ajustei o teste pra ficar mais semântico.

2023-04-11 19:40 UTC, wermesonsl approved these changes

2024-05-21 13:53 UTC, danilo-moreira-brisa commented
This PR is being closed because we are removing Stitches dependency from this project and this feature is majorly done with this library.
We are going to re-do this component with Styled Components and we will use this code as base to do the new implementation.

2024-05-21 13:53 UTC, closed without merging